backendpmk/protected/models/User.php
<?php

/**
 * This is the model class for table "user".
 *
 * The followings are the available columns in table 'user':
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $user_sektoralsub_id
 * @property integer $level
 *
 * The followings are the available model relations:
 * @property Berita[] $beritas
 * @property Brafaks[] $brafaks
 * @property Deklarasi[] $deklarasis
 * @property Implementasi[] $implementasis
 * @property Kegiatan[] $kegiatans
 * @property Kongres[] $kongres
 * @property Meeting[] $meetings
 * @property Sektoral[] $sektorals
 * @property Sektoralsub[] $sektoralsubs
 * @property Summit[] $summits
 * @property Tindak[] $tindaks
 * @property Sektoralsub $userSektoralsub
 */
class User extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username, auth_key, password_hash, email, created_at, updated_at', 'required'),
			array('status, created_at, updated_at, user_sektoralsub_id, level', 'numerical', 'integerOnly'=>true),
			array('username, password_hash, password_reset_token, email', 'length', 'max'=>255),
			array('auth_key', 'length', 'max'=>32),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, username, auth_key, password_hash, password_reset_token, email, status, created_at, updated_at, user_sektoralsub_id, level', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'beritas' => array(self::HAS_MANY, 'Berita', 'berita_user_id'),
			'brafaks' => array(self::HAS_MANY, 'Brafaks', 'brafaks_user_id'),
			'deklarasis' => array(self::HAS_MANY, 'Deklarasi', 'deklarasi_user_id'),
			'implementasis' => array(self::HAS_MANY, 'Implementasi', 'implementasi_user_id'),
			'kegiatans' => array(self::HAS_MANY, 'Kegiatan', 'kegiatan_user_id'),
			'kongres' => array(self::HAS_MANY, 'Kongres', 'kongres_user_id'),
			'meetings' => array(self::HAS_MANY, 'Meeting', 'meeting_user_id'),
			'sektorals' => array(self::HAS_MANY, 'Sektoral', 'sektoral_user_id'),
			'sektoralsubs' => array(self::HAS_MANY, 'Sektoralsub', 'sektoralsub_user_id'),
			'summits' => array(self::HAS_MANY, 'Summit', 'summit_user_id'),
			'tindaks' => array(self::HAS_MANY, 'Tindak', 'tindak_user_id'),
			'userSektoralsub' => array(self::BELONGS_TO, 'Sektoralsub', 'user_sektoralsub_id'),
			'level0' => array(self::BELONGS_TO, 'Userlevel', 'level'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'username' => 'Username',
			'auth_key' => 'Auth Key',
			'password_hash' => 'Password Hash',
			'password_reset_token' => 'Password Reset Token',
			'email' => 'Email',
			'status' => 'Status',
			'created_at' => 'Created At',
			'updated_at' => 'Updated At',
			'user_sektoralsub_id' => 'User Sektoralsub',
			'level' => 'Level',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('auth_key',$this->auth_key,true);
		$criteria->compare('password_hash',$this->password_hash,true);
		$criteria->compare('password_reset_token',$this->password_reset_token,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('created_at',$this->created_at);
		$criteria->compare('updated_at',$this->updated_at);
		$criteria->compare('user_sektoralsub_id',$this->user_sektoralsub_id);
		$criteria->compare('level',$this->level);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function validatePassword($pass){
		if( $this->auth_key === $this->hashPassword($pass,$this->password_hash)){
			return TRUE;
		}
		return FALSE;
	}

	public function hashPassword($password,$salt){
		return md5("pmk2020-".$password.$salt);
	}

	public function generateHash(){
		return uniqid("pmk2020-",TRUE);
	}
}

backendpmk/protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('profile','updateprofile'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionProfile($id){
		$model = $this->loadModel($id);
		$this->render('profile',array(
			'model'=>$model,
		));
	}

    public function actionUpdateprofile()
    {
        $return=array(
			'status'=>0,
			'message'=>'Anda tidak diizinkan untuk melakukan akses.',
			'data'=>array(),
		);

        if(Yii::app()->request->isPostRequest){

            $parser = new CHtmlPurifier();
            $id = $parser->purify($_POST["input_id"]);
            $input_username = $parser->purify($_POST["input_username"]);
            $input_email = $parser->purify($_POST["input_email"]);

            $error = false;
            $errMsg = "";

            if(strlen($input_username)==0)
            {
                $errMsg .= "Username Tidak Boleh Kosong<br>";
                $error = true;
            }
            else if(strlen($input_email)==0)
            {
                $errMsg .= "Email Tidak Boleh Kosong<br>";
                $error = true;
            }

			//update
            else if(!$error)
            {
                $model = $this->loadModel($id);
                $model->username = $input_username;
                $model->email = $input_email;
                if($model->save()){
                    $return['status'] = 1;
                    $return['message'] = "Profile Berhasil Diupdate.";
                }else{
                    $return['message'] = "Profile Gagal Diupdate";
                }
            }
            else if($error)
            {
                $return['status'] = 2;
                $return['message'] = $errMsg;
            }
        }

        echo json_encode($return);

    }


	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

}

backendpmk/protected/views/user/profile.php
<?php
/* @var $this MeetingController */
/* @var $model Meeting */

$this->breadcrumbs=array(
	'User'=>array('profile'),
	$model->id
);

/* $this->menu=array(
	array('label'=>'List Meeting', 'url'=>array('index')),
	array('label'=>'Create Meeting', 'url'=>array('create')),
	array('label'=>'Update Meeting', 'url'=>array('update', 'id'=>$model->meeting_id)),
	array('label'=>'Delete Meeting', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->meeting_id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Meeting', 'url'=>array('admin')),
); */

	Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/public/plugins/datatables/dataTables.bootstrap4.min.css');
	Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/public/plugins/datatables/buttons.bootstrap4.min.css');
	Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/public/plugins/datatables/responsive.bootstrap4.min.css');
	Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/public/plugins/datatables/select.dataTables.min.css');
	Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/public/plugins/sweet-alert2/sweetalert2.min.css');
	Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl."/public/plugins/handsontable/dist/handsontable.full.min.css");
	Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/public/plugins/select2/css/select2.min.css');
	Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/public/plugins/summernote/summernote-bs4.css');
?>

<div class="page-title-box">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title">Profile Pengguna</h1>
            </div>
        </div>
    </div>
</div>
<div class="page-content-wrapper">
    <div class="container-fluid">
	<div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="mt-0 header-title mb-4"><?= $model->username ?></h4>
						<div id="loading">
                                    <div id="progstat">
                                        <div class="row">
                                            <div class="col-md-3"></div>
                                            <div class="col-md-6" style="background:white;border: 4px solid black;"><h1><img src="<?php echo Yii::app()->baseUrl;?>/images/reload.gif"> Loading... </h1></div>
                                            <div class="col-md-3"></div>
                                        </div>
                                    </div>
                                </div>
                        <div style="width:100%;overflow-x:scroll;">
                        <div class="row">
                            <div class="col-md-2">
                                <button style="float:left;" id="btn-u" type="button" class="btn btn-u btn-success waves-effect waves-light">Update Profile Pengguna</button>
                            </div>
                            <div class="col-md-10"></div>
                        </div>
                        <br>
						<?php $this->widget('zii.widgets.CDetailView', array(
							'data'=>$model,
							'attributes'=>array(
								'username',
								'email',
								'level0.userlevel',
								'userSektoralsub.sektoralsub_nama'
							),
						)); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade form-update-profile" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="f_title" class="modal-title mt-0">Update Profile <?= $model->username ?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            
			<form id="form-update-profile" method="post" enctype="multipart/form-data">        
                <input type="hidden" id="f_id" name="input_id" value="<?= Yii::app()->user->id ?>" />      
                <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Username</label><br>
                                    <input value="<?= $model->username ?>" type="text" id="f_username" name="input_username" class="form-control" placeholder="Username"/>
                                </div>
                            </div>
							<div class="col-md-12">
                                <div class="form-group">
                                    <label>Email</label><br>
                                    <input value="<?= $model->email ?>" type="text" id="f_email" name="input_email" class="form-control" placeholder="Email"/>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="modal-footer">
                    <button id="btn-form" type="submit button" class="btn btn-primary waves-effect waves-light">Simpan</button>
                </div>
                </form>
        </div>
    </div>
</div>
<?php
	Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/jquery.dataTables.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/dataTables.bootstrap4.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/dataTables.buttons.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/buttons.bootstrap4.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/jszip.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/pdfmake.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/vfs_fonts.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/buttons.html5.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/buttons.print.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/buttons.colVis.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/dataTables.responsive.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/responsive.bootstrap4.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/datatables/dataTables.select.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/sweet-alert2/sweetalert2.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/handsontable/dist/handsontable.full.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/select2/js/select2.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/public/plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js', CClientScript::POS_END);
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/public/plugins/summernote/summernote-bs4.min.js', CClientScript::POS_END);
	Yii::app()->clientScript->registerScript('initdatatable', '

        function show(z){
            document.getElementById(z).style.display="block";
        }
        function hide(z){		
            document.getElementById(z).style.display="none";	
        }

		$(".btn-u").on("click", function(){    
            $(".form-update-profile").modal("show");
        });

		$("#form-update-profile").submit(function(event){
			$("#btn-form").attr("disabled",true);
            event.preventDefault();

			var formdata = new FormData(this);
			$.ajax({
                url: "'.Yii::app()->createUrl("user/updateprofile").'",
                type: "POST",
                data:  formdata,
                contentType: false,
                cache: false,
                processData:false,
                beforeSend : function(event){
                    $("#loading").css("display", "block");
                },
                success: function(result) {
                    $("#loading").css("display", "none");
                    var res = JSON.parse(result);
                    var type="error";
                    var msg=res.message;
                    var status = res.status;
                    if(res.status == 1){
                        type="success";
                    }
                   
                    swal({
                        title: "result",
                        text: msg,
                        type: type,
                        showCancelButton: false,
                        confirmButtonClass: "btn btn-success",
                    }).then(function () {
                        $("#btn-form").attr("disabled",false);
                        $(".form-deklarasi").modal("hide");
                        if(status!=2){
                            location.reload();
                        }   
                    }, function (dismiss) {
                    });                    
                }
            });  
		});

		$(document).ready(function() {
			$(".text_wysiwyg").summernote({
				toolbar: [
					["font", ["bold", "underline", "clear"]],
					["para", ["ul", "ol", "paragraph"]],
					["view", ["fullscreen", "codeview", "help"]],
				]
			});
		} );
	');
?>