controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\MeetingAll;
use app\models\Berita;
use app\models\ContactForm;
use app\models\Config;
use yii\helpers\HtmlPurifier;
use yii\helpers\Url;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout','viewmeeting','viewberita'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    // 'viewmeeting' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $querydata = Yii::$app->db->createCommand('SELECT * FROM berita ORDER BY berita_id DESC LIMIT 5');
		$databerita = $querydata->queryAll();
        
        $querysektoral = Yii::$app->db->createCommand('SELECT * FROM meeting_all_name ORDER BY all_id DESC LIMIT 5');
		$datasektoral = $querysektoral->queryAll();
		
		$querylinkk = Yii::$app->db->createCommand('SELECT * FROM link where link_show=1 ORDER BY link_nama ASC');
        $datalinkk = $querylinkk->queryAll();

        return $this->render('index',[
            'databerita' => $databerita,
            'datasektoral' => $datasektoral,
            'datalinks' => $datalinkk,
        ]);
    }

    public function actionLatarbelakang(){
        $sql="SELECT * FROM config WHERE alias='about'";
        $data=Yii::$app->db->createCommand($sql)->queryOne();

        return $this->render('latarbelakang',[
            'data'=>$data
        ]);
    }

    public function actionBadansektoral(){
        $sql="SELECT k.kl_id,k.kl_nama,s.sektoral_id,s.sektoral_nama,s.sektoral_singkatan,ss.sektoralsub_id,ss.sektoralsub_nama ,ss.sektoralsub_singkatan
        FROM sektoralsub ss
        LEFT JOIN sektoral s ON s.sektoral_id=ss.sektoralsub_sektoral_id
        LEFT JOIN kl k ON k.kl_id=s.sektoral_kl_id
        ORDER BY k.kl_id,s.sektoral_id,ss.sektoralsub_id";
        $data=Yii::$app->db->createCommand($sql)->queryAll();

        return $this->render('badansektoral',[
            'data'=>$data
        ]);
    }

    public function actionEntitas(){
        $data="entitas";
        return $this->render('entitas',[
            'data'=>$data
        ]);
    }

    public function actionViewmeeting($id){
        $return=array(
            'status'=>0,
            'message'=>'data tidak ditemukan',
            'data'=>''
        );
        $model = MeetingAll::find(1)
                ->where('all_id=:id', [':id' => $id])
                ->one();
        if($model){
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $return=array(
                'status'=>1,
                'message'=>'data tidak ditemukan',
                'data'=>array(
                    'id'=>$model->all_id,
                    'foto'=>$model->foto,
                    'judul'=>$model->title,
                    'lokasi'=>$model->lokasi,
                    'tanggal'=>$model->tanggal,
                    'ketua1'=>$model->ketua1,
                    'ketua2'=>$model->ketua2,
                    'tindaklanjut'=>$model->tindaklanjut,
                )
            );
        }
        
        return $return;
    }

    public function actionViewberita($id){
        $homeUrl=Url::home(true).'..';
        $return=array(
            'status'=>0,
            'message'=>'data tidak ditemukan',
            'data'=>''
        );
        $model = Berita::find(1)
                ->where('berita_id=:id', [':id' => $id])
                ->one();
        if($model){
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $return=array(
                'status'=>1,
                'message'=>'data ditemukan',
                'data'=>array(
                    'id'=>$model->berita_id,
                    'foto'=>$homeUrl.'/assets/berita/'.$model->berita_foto,
                    'judul'=>$model->berita_judul,
                    'berita'=>$model->berita_overview,
                    'tanggal'=>Yii::$app->myHelper->indonesian_date($model->berita_adddate),
                )
            );
        }
        
        return $return;
    }

    public function actionResultsearch($keyword){
        $cleankeyword=HtmlPurifier::process($keyword);
        echo $cleankeyword;
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $a=Config::find(1)
        ->where('alias=:alias', [':alias' =>'about'])
        ->one();
        return $this->render('about',[
            'about'=>$a
        ]);
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">
    <div class="body-content">
        <div class="row">
            <div class="col-lg-9">
                <div class="card m-t-10">
                    <div class="card-header"><h1><?php echo $about->judul;?></h1></div>
                    <div class="card-body">
                        <?php echo $about->isi; ?>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                
            </div>
        </div>

    </div>
</div>

views/site/badansektoral.php
<?php
use yii\helpers\Url;
use yii\web\View;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
    
?>
<style>
.list-group-item{
    padding:0px 0px 0px 0px;
}

.cursor-pointer{
  cursor: pointer;
}
</style>
<div class="site-index">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-header">Daftar Badan Sektoral</div>
                    <div class="card-body">
                        <div style="width:100%;overflow-x:scroll;">
                        <table 
                            id="listsektoral"
                            class="table"
                            style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                                <tr>
                                    <th scope="col" style="width: 10%;">#</th>
                                    <th scope="col" style="width: 30%;">Kementrian / Lembaga</th>
                                    <th scope="col" style="width: 30%;">Sektoral</th>
                                    <th scope="col" style="width: 30%;">Sektoral Sub</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    $tr="";
                                    $i=1;
                                    foreach($data as $r){
                                        $tr.="<tr>
                                        <td>".$i."</td>
                                        <td>".$r['kl_nama']."</td>
                                        <td>".($r['sektoral_singkatan'] ? "[".$r['sektoral_singkatan']."] ".$r['sektoral_nama'] : "")."</td>
                                        <td>".($r['sektoralsub_singkatan'] ? "[".$r['sektoralsub_singkatan']."] ".$r['sektoralsub_nama'] : "")."</td>
                                        </tr>";

                                        $i++;
                                    }
                                    echo $tr;
                                ?>
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/entitas.php
<?php
use yii\helpers\Url;
use yii\web\View;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
    
?>
<style>
.list-group-item{
    padding:0px 0px 0px 0px;
}

.cursor-pointer{
  cursor: pointer;
}
</style>
<div class="site-index">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-header"><?php echo $data;?></div>
                    <div class="card-body">
                    <?php echo $data;?>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Url;
use yii\web\View;
/* @var $this yii\web\View */
$homeUrl=Url::home(true).'..';
    function readmore($teks, $jumlahkata){
        $string=explode(" ", $teks);
        $hasil="";
        for($i=0;$i<$jumlahkata;$i++){ 
            $hasil .= $string[$i]." "; 
        }
        return $hasil;
    }
$this->title = 'Forkom ASEAN';
    $kementrian="";
    $lembaga="";
    foreach($datalinks as $links){
	    if($links['link_opt']==1){
            $kementrian.='<li class="list-group-item"><a target="_blank" href="'.$links['link_href'].'" class="nav-link">'.$links['link_nama'].'</a></li>';
		} else {
            $lembaga.='<li class="list-group-item"><a target="_blank" href="'.$links['link_href'].'" class="nav-link">'.$links['link_nama'].'</a></li>';
        }
    }

    $listsektoral="";
    foreach($datasektoral as $sektoral){
        $ketua="Ketua Rapat : ";
        if(!empty($sektoral['ketua1']) && !empty($sektoral['ketua2'])) $ketua.=$sektoral['ketua1']." dan ".$sektoral['ketua2'];
		if(empty($sektoral['ketua1'])) $ketua.=$sektoral['ketua2'];
        if(empty($sektoral['ketua2'])) $ketua.=$sektoral['ketua1'];
        
        $listsektoral.='<li data-target=".bd-example-modal-xl" id="'.$sektoral['all_id'].'" class="list-group-item cursor-pointer view_sektoral">
            <a class="sektoral nav-link"><strong>'.$sektoral['title'].'</strong><br>
            '.$sektoral['lokasi'].', '.Yii::$app->myHelper->indonesian_date($sektoral['tanggal']).'
            </a>
        </li>';
    }
?>
<style>
.list-group-item{
    padding:0px 0px 0px 0px;
}

.cursor-pointer{
  cursor: pointer;
}
</style>
<div class="site-index">
    <div class="body-content">
        <div class="row">
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-body">
                        <?php
                            $i=0;
                            $li=array();
                            $items=array();
                            $linkJudul=array();
                            $active="";
                            foreach($databerita as $berita){
                                array_push($linkJudul,'<li class="list-group-item"><img src="'.$berita['berita_foto'].'" style="width:150px" ><a target="_blank" href="#" class="nav-link">'.$berita['berita_judul'].'</a></li>');
                                $image=$this->theme->baseUrl."/images/slideshow/img-2.jpg";
                                if($i==0){
                                   $active='active'; 
                                } else {
                                    $active="";
                                }

                                if($berita['berita_foto']!=''){
                                    $image=$homeUrl.'/assets/berita/'.$berita['berita_foto'];
                                }
                                $item='<div class="carousel-item '.$active.'">
                                    <img src="'.$image.'" alt="berita_'.$i.'" class="d-block img-fluid">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5>'.$berita['berita_judul'].'</h5>
                                    
                                    </div>
                                </div>';
                                array_push($items,$item);

                                $i++;        
                            }
                        ?>

                        <div id="carouselExampleCaption" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner" role="listbox">
                                <?php echo implode(" ",$items);?>
                            </div>
                            
                            <a class="carousel-control-prev" href="#carouselExampleCaption" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            
                            <a class="carousel-control-next" href="#carouselExampleCaption" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-4 "><a href="http://asean.org/"><img src="<?php echo $this->theme->baseUrl; ?>/images/logo/asean.png" class="img-responsive rounded mx-auto d-block"></a></div>
                    <div class="col-md-4"><a href="http://www.aseanstats.org/"><img src="<?php echo $this->theme->baseUrl; ?>/images/logo/acss.png" class="img-responsive rounded mx-auto d-block"></a></div>
                    <div class="col-md-4"><a href="http://www.kemenkopmk.go.id/"><img src="<?php echo $this->theme->baseUrl; ?>/images/logo/pmk.png" class="img-responsive rounded mx-auto d-block"></a></div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">Berita</div>
                            </div>
                            <div class="card-body">
                                <?php foreach($databerita as $berita): ?>
                                    <?php $image=$homeUrl.'/assets/berita/'.$berita['berita_foto']; ?>
                                    <div class="row mb-3">
                                        <div class="col-md-3">
                                            <img src="<?= $image ?>" width="100%" />
                                        </div>
                                        <div class="col-md-9">
                                            <strong><?= $berita['berita_judul'] ?></strong><br>
                                            <small><?= Yii::$app->myHelper->indonesian_date($berita['berita_adddate'])?> </small>
                                            <small><?php
                                            $b=strip_tags($berita['berita_overview']);
                                            $output="";
                                            if(str_word_count($b) > 200){
                                               $output= readmore($b,200);
                                               echo '<p>'.$output.' ... <a  data-target=".bd-example-modal-xl" id="brt_'.$berita['berita_id'].'" class="view_berita" href="#">Selengkapnya</a></p>';
                                            } else {
                                               echo $berita['berita_overview'];
                                            }
                                            ?></small>
                                        </div>
                                    </div>
                                    <hr>
                                <?php endforeach ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Kementrian Terkait</h4>
                    </div>
                    <div>
                        <ul class="list-group">
                            <?php echo $kementrian;?>
                        </ul>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Lembaga Terkait</h4>
                    </div>
                    <div>
                        <ul class="list-group">
                            <?php echo $lembaga;?>
                        </ul>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Rapat</h4>
                    </div>
                    <div>
                        <ul class="list-group">
                            <?php  echo $listsektoral; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="modal fade bd-example-modal-xl">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="s_title" class="modal-title h4">...</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <i class="anticon anticon-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="text-center" id="s_img"></div>
                <div id="s_body"></div>
            </div>
        </div>
    </div>
</div>


<?php

$url=Url::to(['site/viewmeeting']);
$script ='
    $(".view_sektoral").on("click", function(){
        var id=$(this).attr("id");
        var url="'.Url::to(['site/viewmeeting']).'";
        $.ajax({
            url: url,
            type: "GET",
            data:{id:id},
            beforeSend : function(event){
                // $("#arcupload").css("opacity",".5");
                // $("#loading").css("display", "block");
                $("#s_title").html("");
                $("#s_body").html("");
            },
            success: function(res) {
                // $("#loading").css("display", "none");
                if(res.status=="1"){
                    var ketua="";
                    if( !!res.data.ketua1 && !!res.data.ketua2 ){
                        ketua="Ketua Rapat : "+res.data.ketua1+" dan "+res.data.ketua2;
                    } else if(!!res.data.ketua1){
                        ketua="Ketua Rapat : "+res.data.ketua1;
                    } else {
                        ketua="Ketua Rapat : "+res.data.ketua2;
                    }

                    var lokasi=res.data.lokasi+", "+res.data.tanggal+"<br>"+ketua;
                    var tl="-";
                    if(!!res.data.tindaklanjut){
                        tl=res.data.tindaklanjut;
                    }
                    
                    $("#s_title").html(res.data.judul);
                    $("#s_body").html(lokasi+"<br>Tindak Lanjut : <br>"+unescape(tl));
                    if(!!res.data.foto){
                        $("#s_img").html("<img src=\'+res.data.foto+\' class=\'imgberita img-responsive\'>");
                    }
                } else {
                    alert(res.message);
                }
            }
        });
        $($(this).data("target")).modal("show");
    });

    $(".view_berita").on("click", function(){
        var id=$(this).attr("id");
        var tmp=id.split("_");
        
        var url="'.Url::to(['site/viewberita']).'";
        $.ajax({
            url: url,
            type: "GET",
            data:{id:tmp[1]},
            beforeSend : function(event){
                $("#s_title").html("");
                $("#s_body").html("");
                $("#s_img").html("");
            },
            success: function(res) {
                if(res.status=="1"){
                    $("#s_title").html(res.data.judul);
                    $("#s_body").html(res.data.tanggal+"<br>"+res.data.berita);
                    if(!!res.data.foto){
                        $("#s_img").html("<img width=\'100%\' src=\'"+res.data.foto+"\' class=\'imgberita img-responsive\'>");
                    }
                } else {
                    alert(res.message);
                }
            }
        });
        $($(this).data("target")).modal("show");
    });

   
';
$this->registerJs($script,View::POS_READY,'popup-handler');
$this->registerCss("
a.nav-link:hover { 
    background-color: #007bff;
    color: white;
}
.sektoral {
    color : #007bff !important;
}
.sektoral:hover {
    background-color: #007bff !important;
    color: white !important;
}
");
?>

views/site/latarbelakang.php
<?php
use yii\helpers\Url;
use yii\web\View;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
    
?>
<style>
.list-group-item{
    padding:0px 0px 0px 0px;
}

.cursor-pointer{
  cursor: pointer;
}
</style>
<div class="site-index">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-header"><?php echo $data['judul'];?></div>
                    <div class="card-body">
                    <?php echo $data['isi'];?>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>